baseurl = "http://blog.moonlightwatch.me/"
languageCode = "en-us"
title = "MoonLightWatch的博客"
theme= "hugo_theme_pickles"
copyright = "&copy; Copyright MoonLightWatch"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  #twitter = "Your Twitter username"
  #facebook = "Your Facebook username"
  #instagram = "Your Instagram username"
  #googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
  github = "moonlightwatch"
  #gitlab = "Your GitLab username"
  #npm = "Your npm username"
  #codepen = "Your CodePen username"
  #dribbble = "Your Dribbble username"
  #fivehundredpx = "Your 500px username" # 500px
  #flickr = "Your Flickr username"
  #pinterest = "Your Pinterest username"
  #tumblr = "Your Tumblr username"
  #vimeo = "Your Vimeo username"
  #youtube = "Your YouTube username"
  #linkedin = "Your LinkedIn username"
  # Disqus shortname
  #disqus = ""
  # Google Analytics API key.
  ga_api_key = "UA-98480829-1"
  author = "MoonLightWatch"
  authorwebsite = "blog.moonlightwatch.me"
  avatar = "/path/to/avatar"
  contact = "mailto:moonlightwatch@hotmail.com"
  bio = "一名程序员"
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "记录我不曾知道的"
  # Logo image. This is displayed ogp image.
  logo = "/path/to/logo"
  favicon = "/path/to/favicon"

